const HELP_DATABASE: Record<string, string> = {
  'loop': `
### Loops in JavaScript
**For Loop**:
\`\`\`javascript
for (let i = 0; i < 5; i++) {
  console.log(i);
}
\`\`\`
**While Loop**:
\`\`\`javascript
while (condition) {
  // do something
}
\`\`\`
  `,
  'function': `
### Functions
**Declaration**:
\`\`\`javascript
function sayHello(name) {
  return "Hello " + name;
}
\`\`\`
**Arrow Function**:
\`\`\`javascript
const add = (a, b) => a + b;
\`\`\`
  `,
  'error': `
### Debugging Errors
1. **Check the console**: Look for red error messages.
2. **Read the line number**: The error message usually tells you where it broke.
3. **Common issues**: Missing \`;\`, typos in variable names, or unclosed \`{\`.
  `,
  'variable': `
### Variables
- \`const\`: Use for values that won't change.
- \`let\`: Use for values that will change.
- \`var\`: Old school, try to avoid it.
  `,
  'console': `
### Console
Use \`console.log(data)\` to print output to the screen.
  `,
  'array': `
### Arrays
\`\`\`javascript
const list = [1, 2, 3];
list.push(4); // Add item
console.log(list[0]); // Access item
\`\`\`
  `
};

import { generateCompletion } from './aiService';

export const getHelpResponse = async (query: string): Promise<string> => {
  const lowerQuery = query.toLowerCase();

  if (!lowerQuery) return "Please type a keyword to search for help (e.g., 'loop', 'function').";

  // 1. Check local database first for instant answers to common topics
  // This reduces load and lag for simple things
  const match = Object.keys(HELP_DATABASE).find(key => lowerQuery.split(' ').includes(key));
  if (match) {
    return HELP_DATABASE[match] + "\n\n*(Sourced from Local Knowledge Base)*";
  }

  // 2. Fallback to AI for complex queries
  try {
    const prompt = `You are a helpful JavaScript coding assistant. The user is asking: "${query}". Provide a concise, helpful explanation with a code example if relevant. Use Markdown formatting. Keep it short and sweet.`;

    const { response, error } = await generateCompletion(prompt);

    if (error) {
      return `Cannot connect to AI Assistant. Please ensure Ollama is running.\n\nError: ${error}`;
    }

    return response + "\n\n*(Generated by Local DeepSeek Coder)*";
  } catch (e) {
    return "An unexpected error occurred while contacting the AI assistant.";
  }
};
